"""Added default value to status column

Revision ID: badfa0a78de2
Revises: 9a15b4430b68
Create Date: 2021-10-25 18:32:00.504015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badfa0a78de2'
down_revision = '9a15b4430b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assessments_title', table_name='assessments')
    op.create_index(op.f('ix_assessments_title'), 'assessments', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_title'), table_name='assessments')
    op.create_index('ix_assessments_title', 'assessments', ['title'], unique=False)
    # ### end Alembic commands ###
